name: SSDLC Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

permissions: {}

jobs:
  code-security-analysis:
    permissions:
      security-events: write # required for uploading code scanning alerts
    uses: mozilla/ssdlc-actions/.github/workflows/code-security-analysis-public-repo.yml@ca8be48f3c06204fb16a3bd5ffa6d916782bbc76 # v1
